name: Compress images
on: 
  push:
    branches: main
jobs:
  build:
    name: Optimise Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Compress Images
        run: |
          npm install -g imageoptim-cli
          imageoptim images/*
